### Libraries: NumPy & Pandas

In [ ]:
import pandas as pd
import numpy as np
# import calendar as c

**Q1. Load the given retail sales dataset into a Pandas DataFrame and display the first 5 rows along with the dataset information to understand its structure.**

In [24]:
df = pd.read_csv('retail_dataset .csv')

print(df.info())
df.head(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    100 non-null    object
 1   Customer ID       100 non-null    object
 2   Product Category  97 non-null     object
 3   Quantity          98 non-null     float64
 4   Price             95 non-null     float64
 5   Date              100 non-null    object
 6   Region            98 non-null     object
dtypes: float64(2), object(5)
memory usage: 5.6+ KB
None

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region
0,T001,C015,Books,7.0,167.0,02-02-2023,North
1,T002,C004,Toys,4.0,374.0,17-02-2023,South
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South
4,T005,C022,Books,7.0,282.0,27-07-2024,West

**Q2. Inspect the dataset and identify missing values in each column. Display the total number of missing values present in the dataset.**

In [25]:
df.isnull().sum()

Transaction ID      0
Customer ID         0
Product Category    3
Quantity            2
Price               5
Date                0
Region              2
dtype: int64

**Q3. Replace missing values in the Quantity and Price columns with their respective mean values using Pandas.**

In [26]:
df['Quantity'].fillna(df['Quantity'].mean(), inplace=True)

df['Price'].fillna(df['Price'].mean(), inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_7128\991810646.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Quantity'].fillna(df['Quantity'].mean(), inplace=True)
C:\Users\DELL\AppData\Local\Temp\ipykernel_7128\991810646.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Price'].fillna(df['Price'].mean(), inplace=True)

**Q4. Remove all rows where the Product Category or Region column contains missing values.**

In [27]:
df = df.dropna(subset=['Product Category', 'Region'])

**Q5. Create a new column called Revenue using NumPy, where:**
- **Revenue = Quantity × Price**
- **Display the updated dataset with the new column.**

In [28]:
df['Revenue'] = np.multiply(df['Quantity'], df['Price'])

df.head()

,Transaction ID,Customer ID,Product Category,Quantity,Price,Date,Region,Revenue
0,T001,C015,Books,7.0,167.0,02-02-2023,North,1169.0
1,T002,C004,Toys,4.0,374.0,17-02-2023,South,1496.0
2,T003,C033,Furniture,8.0,1059.0,17-05-2024,South,8472.0
3,T004,C047,Groceries,5.0,304.0,11-02-2024,South,1520.0
4,T005,C022,Books,7.0,282.0,27-07-2024,West,1974.0

**Q6. Using NumPy, calculate the total revenue generated from all transactions in the dataset.**

In [29]:
print("Total Revenue:", np.sum(df['Revenue']))

Total Revenue: 465529.66058002145

**Q7. Group the dataset by Product Category and calculate the total revenue generated by each category.**

In [30]:
df.groupby('Product Category', as_index=False)['Revenue'].sum()

  Product Category        Revenue
0           Beauty   27647.000000
1            Books   29597.938776
2         Clothing   85006.000000
3      Electronics   93204.315789
4        Furniture  129664.526316
5        Groceries   11978.000000
6           Sports   34484.000000
7             Toys   53947.879699

**Q8. Based on the revenue calculated for each product category, identify the top 3 categories with the highest revenue and the bottom 3 categories with the lowest revenue.**

In [31]:
revByCat = df.groupby('Product Category', as_index=False)['Revenue'].sum()

# Top three
revByCat.sort_values(by='Revenue', ascending=False).head(3)

  Product Category        Revenue
4        Furniture  129664.526316
3      Electronics   93204.315789
2         Clothing   85006.000000

In [32]:
# Bottom three
revByCat.sort_values(by='Revenue', ascending=False).tail(3)

  Product Category       Revenue
1            Books  29597.938776
0           Beauty  27647.000000
5        Groceries  11978.000000

**Q9. Group the dataset by Region and calculate the total revenue generated in each region. Identify the region with the highest revenue and the region with the lowest revenue.**

In [33]:
revByReg = df.groupby('Region', as_index=False)['Revenue'].sum()

# Region with the highest revenue
revByReg.sort_values(by='Revenue', ascending=False).head(1)

  Region        Revenue
1  North  153244.353383

In [ ]:
# Region with the lowest revenue
revByReg.sort_values(by='Revenue', ascending=False).tail(1)

  Region       Revenue
3   West  81197.526316

**Q10. Extract the month from the Date column using Pandas and group the dataset by month to calculate the total monthly revenue. Also, calculate the mean, median, and standard deviation of the Revenue column using NumPy**

In [53]:
# df.isnull().sum()


# Converting Date to datetime and extracting Month
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True)
df['Month'] = df['Date'].dt.month
# df['Month'] = df['Month'].apply(lambda x: c.month_name[x])

# Grouping by Month to calculating total monthly revenue
revByMonth = df.groupby('Month')['Revenue'].sum().reset_index()
print("Total Monthly Revenue:")
print(revByMonth.head())


revArray = df['Revenue'].values
revMean = np.mean(revArray)
revMedian = np.median(revArray)
revStd = np.std(revArray)


print(f"\nRevenue Statistics:")
print(f"Mean: {revMean:.2f}")
print(f"Median: {revMedian:.2f}")
print(f"Standard Deviation: {revStd:.2f}")

Total Monthly Revenue:
   Month       Revenue
0      1  43994.000000
1      2  33028.000000
2      3  10557.000000
3      4  57298.526316
4      5  27915.000000

Revenue Statistics:
Mean: 4900.31
Median: 3282.11
Standard Deviation: 4721.17