### Advanced Pandas

**Q1 Dataset Exploration**<br>
Perform the following exploratory steps:
- Display the first 10 rows
- Display the dataset structure using info()
- Find the number of rows and columns
- Identify the data types of each column

In [101]:
import pandas as pd

df = pd.read_csv("Advanced_pandas_sales_dataset.csv")

# Display the first 10 rows
df.head(10)

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
2,1003,2024-01-26,Anita,Mumbai,West,Phone,Electronics,2328,1,0.20,66.47
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
6,1007,2024-06-24,Dev,Chennai,East,Monitor,Electronics,1170,5,0.20,22.83
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
9,1010,2024-12-25,Pooja,Ahmedabad,North,Phone,Electronics,2711,8,0.00,477.32

In [102]:
# Display the dataset structure using info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230 entries, 0 to 229
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    230 non-null    int64
 1   Order_Date  230 non-null    object
 2   Customer    230 non-null    object
 3   City        230 non-null    object
 4   Region      230 non-null    object
 5   Product     230 non-null    object
 6   Category    230 non-null    object
 7   Sales       230 non-null    int64
 8   Quantity    230 non-null    int64
 9   Discount    230 non-null    float64
 10  Profit      230 non-null    float64
dtypes: float64(2), int64(3), object(6)
memory usage: 19.9+ KB

In [103]:

# Find the number of rows and columns
print(df.shape, "\n")

# Identify the data types of each column
df.dtypes

(230, 11)

Order_ID        int64
Order_Date     object
Customer       object
City           object
Region         object
Product        object
Category       object
Sales           int64
Quantity        int64
Discount      float64
Profit        float64
dtype: object

**Q2 Sales Filtering Analysis, Filter the dataset to display:**
- Orders where Sales > 3500
- Orders where Region = "East" and Sales > 2500
- Explain what insights you observe.

In [104]:
# Orders where Sales > 3500
df[df['Sales'] > 3500]

# df[df.Sales > 3500]

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
7,1008,2024-03-18,Kavya,Kolkata,East,Phone,Electronics,4693,7,0.05,918.49
8,1009,2024-10-31,Kavya,Ahmedabad,East,Phone,Electronics,5071,6,0.10,707.55
10,1011,2024-06-30,Neha,Delhi,South,Printer,Office,5977,6,0.00,1578.32
...,...,...,...,...,...,...,...,...,...,...,...
219,1220,2024-03-22,Meera,Bangalore,West,Phone,Electronics,5986,7,0.05,986.70
222,1223,2024-03-04,Meera,Ahmedabad,South,Phone,Electronics,4356,6,0.10,416.87
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

In [105]:
# Orders where Region = "East" and Sales > 2500
df[(df.Region == "East") | (df.Sales > 2500)]

,Order_ID,Order_Date,Customer,City,Region,Product,Category,Sales,Quantity,Discount,Profit
0,1001,2024-10-01,Priya,Hyderabad,East,Mouse,Accessories,1735,7,0.00,307.52
1,1002,2024-05-03,Sneha,Kolkata,East,Monitor,Electronics,807,2,0.15,49.89
3,1004,2024-06-06,Sara,Pune,East,Keyboard,Accessories,3933,3,0.20,-71.66
4,1005,2024-10-15,Rahul,Bangalore,South,Monitor,Electronics,3550,2,0.20,146.30
5,1006,2024-07-04,Pooja,Bangalore,West,Printer,Office,3073,8,0.20,191.58
...,...,...,...,...,...,...,...,...,...,...,...
223,1224,2024-01-07,Dev,Bangalore,East,Tablet,Electronics,4115,4,0.05,870.03
225,1226,2024-06-14,Anita,Ahmedabad,East,Laptop,Electronics,5647,2,0.15,662.00
227,1228,2024-01-14,Vikas,Chennai,North,Tablet,Electronics,2682,7,0.15,119.82
228,1229,2024-09-04,Priya,Pune,East,Tablet,Electronics,2635,8,0.00,531.76
229,1230,2024-04-13,Meera,Kolkata,North,Monitor,Electronics,5087,8,0.10,416.72

Explain what insights you observe.

**Q3 Customer Purchase Analysis**
- Identify the top 5 customers based on total sales.
- Hint: Use GroupBy with aggregation.

In [106]:
df.groupby('Customer')['Sales'].sum().nlargest(5).reset_index()

  Customer  Sales
0    Nitin  59820
1      Raj  58416
2    Rahul  52291
3      Dev  48500
4     Isha  46818

**Q4 Regional Sales Performance**
- Calculate the total sales generated by each region.
- Then identify:
  - Which region generated the highest revenue?

In [107]:
# Calculate the total sales generated by each region.
salesByRegion = df.groupby('Region')['Sales'].sum().reset_index()
print(salesByRegion)

# Which region generated the highest revenue?
topRevenue = salesByRegion[salesByRegion["Sales"] == salesByRegion["Sales"].max()]
topRevenue

  Region   Sales
0   East  232675
1  North  158210
2  South  183108
3   West  170227

  Region   Sales
0   East  232675

**Q5 Product Performance Analysis**
- Calculate the total quantity sold for each product.
- Which product appears to be the most popular?

In [108]:
# Calculate the total quantity sold for each product.
quantityByProduct = df.groupby('Product')['Quantity'].sum().reset_index()
print(quantityByProduct)

# Which product appears to be the most popular?
mostPopular = quantityByProduct[quantityByProduct["Quantity"] == quantityByProduct["Quantity"].max()]
mostPopular

      Product  Quantity
0  Headphones       115
1    Keyboard       110
2      Laptop       140
3     Monitor       156
4       Mouse       122
5       Phone       151
6     Printer       108
7      Tablet       150

   Product  Quantity
3  Monitor       156

**Q6 Multi-Level Grouping**
- Group the dataset by: Region and Category
- Calculate the total sales for each combination.
- What insights can you derive from this analysis?

In [109]:
# Group the dataset by: Region and Category
# Calculate the total sales for each combination.
df.groupby(['Region', 'Category'])['Sales'].sum().unstack()

Category  Accessories  Electronics  Office
Region
East            57646       160907   14122
North           62052        70023   26135
South           80914        86690   15504
West            64811        84128   21288

What insights can you derive from this analysis?

**Q7 Pivot Table Creation**<br>
Create a pivot table showing:
- Rows → Region
- Columns → Product
- Values → Total Sales
- Which region sells the most laptops?

In [110]:
pivot_table = df.pivot_table(index='Region', 
                             columns='Product', 
                             values='Sales', 
                             aggfunc='sum', 
                             fill_value=0)

print(pivot_table)
print(f"\nThe region that sells the most laptops is: {pivot_table['Laptop'].idxmax()}")

Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          23899     10845   55568    31299  22902  39667    14122   34373
North         15450     20538    4540    14922  26064  30535    26135   20026
South         24111     23480   23029    19167  33323  18218    15504   26276
West          17159     38499   10826    18178   9153  27850    21288   27274

The region that sells the most laptops is: East

**Q8 Profitability Analysis**
- Calculate the average profit for each product category.
- Which category is most profitable?

In [111]:
# Calculate the average profit for each product category.
avgProfitByCategory = df.groupby('Category')['Profit'].mean().reset_index()
print(avgProfitByCategory)

# Which category is most profitable?
topAvgProfitByCategory = df.groupby('Category')['Profit'].mean().idxmax()
print(f"\n{topAvgProfitByCategory} category is most profitable")

      Category      Profit
0  Accessories  410.603086
1  Electronics  396.462114
2       Office  471.938462

Office category is most profitable

**Q9 Discount Impact Study, Analyze the relationship between discount and profit.**<br>
Tasks:
- Calculate the average profit for each discount level
- Identify whether higher discounts lead to lower profit

In [112]:
# Calculate the average profit for each discount level
avgProfitByDiscountLevel = df.groupby('Discount')['Profit'].mean().reset_index()
print(avgProfitByDiscountLevel,'\n')

# Identify whether higher discounts lead to lower profit
correlation = df['Discount'].corr(df['Profit'])
if correlation < 0 :
    print('Yes higher discounts leads to lower profit')
else :
    print('No higher discounts does not lead to lower profit')

   Discount      Profit
0      0.00  751.210588
1      0.05  531.368039
2      0.10  346.460513
3      0.15  237.191400
4      0.20   90.026923

Yes higher discounts leads to lower profit

**Q10 End-to-End Data Wrangling Task**<br>
Perform the following workflow:
- Filter the dataset where Sales > 3000
- Group data by Region and Product
- Calculate total sales
- Reshape the result into a pivot table
- Explain the business insights obtained from this analysis.

In [113]:
# Filter the dataset where Sales > 3000
higherSalesdf = df[df['Sales'] > 3000]

# Group data by Region and Product
# Calculate total sales
# Reshape the result into a pivot table
pivot_result = higherSalesdf.pivot_table(index='Region', 
                                         columns='Product', 
                                         values='Sales', 
                                         aggfunc='sum', 
                                         fill_value=0)

pivot_result

Product  Headphones  Keyboard  Laptop  Monitor  Mouse  Phone  Printer  Tablet
Region
East          14469      9642   44096    16420  19000  29500     3696   29229
North          5326     15653    4540     5087  22209  24670    17185    3392
South         10026     19249   17950    14921  26928  18218    14143   19613
West          13898     33380    5922    14354   3511  15653    12648   17185

Explain the business insights obtained from this analysis.